# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Tobiah"
subtitle: "A walk through nature!"
author: "Tobiah Gorneau"
header:
 title: "Photography"
 subtitle: "by Tobiah"
footer:
 name: "Hi! My name is Tobiah"
 bio: "I started wildlife photography at the age of twelve. And the inspiration to start doing this was by watching Austin Stevens, an honestly really bad photographer. But, my inspiration continued when I started waking up at four O’clock in the spring and summer to go and photograph anything I could find. And eventually I was getting up early almost every day, than I started watching videos on wildlife photography and learned some photography tricks specifically for wildlife. These certainly assisted my photography."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/"
  twitter: "https://www.twitter.com/"
  instagram: "https://www.instagram.com/"
  dribbble: "https://dribbble.com/"
  linkedin: "https://in.linkedin.com/in/"
  github: "https://www.github.com/"
