# Base configs
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Tobiah"
subtitle: "A walk through nature!"
author: "Tobiah Gorneau"
header:
 title: "Photography"
 subtitle: "by Tobiah"
footer:
 name: "Hey there, my name is Tobiah"
 bio: "I am a photographer from Maine."
web_design: "AJ"
social_urls:
  facebook: "https://www.facebook.com/"
  twitter: "https://www.twitter.com/"
  instagram: "https://www.instagram.com/"
  dribbble: "https://dribbble.com/"
  linkedin: "https://in.linkedin.com/in/"
  github: "https://www.github.com/"
